os: osx
osx_image: xcode10.1
language: objective-c
branches:
  only:
    - master

before_install:
  - pod repo update

script:
  xcodebuild -workspace Jared.xcworkspace -scheme JaredUI test ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO